server:
  port: 2202
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Nghia2013864@}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: a1nYW6AFG6sTBTl9ycyicr4wmfojQwtC3ERpLcX2ISo=

logging.level.org.springframework.security: DEBUG